version: '3.3'

volumes:
  postgres:

services:
  db:
    image: postgres
    env_file: ./parser/.env
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432

  parser:
    build: ./parser
    depends_on:
      - db
